export type * from "./contracts.js";

import type {
  AmbiguityReport,
  AssumptionReport,
  IntelligenceSuggestion,
  IntentAnalysis,
  QuestionIntelligenceEngine,
  QuestionRefinementRequest,
  QuestionRefinementResult,
  SemanticTagSuggestion,
  SemantiqPreview
} from "./contracts.js";

const createId = (prefix: string): string =>
  `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2)}`;

export class LocalQuestionIntelligenceEngine implements QuestionIntelligenceEngine {
  private readonly suggestions = new Map<string, IntelligenceSuggestion>();

  async refineQuestion(request: QuestionRefinementRequest): Promise<QuestionRefinementResult> {
    const intent = await this.extractIntent(request.rawInput);
    const ambiguity = await this.analyzeAmbiguity(request.rawInput);
    const assumptions = await this.detectAssumptions(request.rawInput);
    const tags = await this.suggestTags(request.rawInput);
    const improved = this.remember({
      id: createId("suggestion"),
      type: "question-refinement",
      status: "proposed",
      confidence: 0.5,
      explanation:
        "Local scaffold trims whitespace and adds a question mark when missing; production AI must preserve meaning explicitly.",
      payload: { question: this.normalizeQuestion(request.rawInput) },
      createdAt: new Date().toISOString()
    });

    return {
      requestId: request.id,
      originalQuestion: request.rawInput,
      detectedLanguage: request.languageHint ?? "unknown",
      detectedIntent: intent,
      improvedVersion: improved as IntelligenceSuggestion<{ question: string }>,
      alternativeVersions: [
        this.remember({
          id: createId("suggestion"),
          type: "alternative-question",
          status: "proposed",
          confidence: 0.4,
          explanation: "Simple version generated by local scaffold.",
          payload: { label: "simple", question: this.normalizeQuestion(request.rawInput) },
          createdAt: new Date().toISOString()
        }) as IntelligenceSuggestion<{ label: string; question: string }>
      ],
      ambiguityReport: ambiguity,
      assumptionReport: assumptions,
      suggestedTags: tags.map(
        (tag) =>
          this.remember({
            id: createId("suggestion"),
            type: "semantic-tag",
            status: "proposed",
            confidence: tag.confidence,
            explanation: tag.explanation,
            payload: tag,
            createdAt: new Date().toISOString()
          }) as IntelligenceSuggestion<SemanticTagSuggestion>
      ),
      duplicateCandidates: [],
      relationSuggestions: [],
      evidenceSuggestions: [
        this.remember({
          id: createId("suggestion"),
          type: "evidence",
          status: "proposed",
          confidence: 0.6,
          explanation: "Evidence search strategy generated without fabricating sources.",
          payload: {
            type: "open-question",
            searchStrategy: `Search for evidence about: ${request.rawInput}`,
            confidence: 0.6,
            fabricated: false
          },
          createdAt: new Date().toISOString()
        }) as QuestionRefinementResult["evidenceSuggestions"][number]
      ],
      semantiqPreview: await this.generateSemantiqPreview(request.rawInput)
    };
  }

  async analyzeQuestion(question: string): Promise<QuestionRefinementResult> {
    return this.refineQuestion({
      id: createId("question-analysis"),
      rawInput: question,
      actorId: "local-question-intelligence",
      contextObjectIds: []
    });
  }

  async improveQuestion(question: string): Promise<IntelligenceSuggestion<{ question: string }>> {
    return this.remember({
      id: createId("suggestion"),
      type: "question-improvement",
      status: "proposed",
      confidence: 0.65,
      explanation:
        "Improvement preserves meaning while adding question punctuation and context prompt.",
      payload: { question: this.normalizeQuestion(question) },
      createdAt: new Date().toISOString()
    }) as IntelligenceSuggestion<{ question: string }>;
  }

  async detectDuplicates(
    question: string,
    candidates: readonly { readonly id: string; readonly text: string }[]
  ): Promise<readonly import("./contracts.js").DuplicateCandidate[]> {
    const terms = new Set(question.toLowerCase().split(/\s+/).filter(Boolean));
    return candidates
      .map((candidate) => {
        const candidateTerms = new Set(candidate.text.toLowerCase().split(/\s+/).filter(Boolean));
        const overlap = [...terms].filter((term) => candidateTerms.has(term)).length;
        const union = new Set([...terms, ...candidateTerms]).size;
        const similarity = union === 0 ? 0 : overlap / union;
        return {
          questionId: candidate.id,
          similarity,
          reason: `Shared ${overlap} semantic terms with the candidate question.`,
          suggestedAction: similarity > 0.7 ? "merge" : "link"
        } as const;
      })
      .filter((candidate) => candidate.similarity > 0.2)
      .sort((left, right) => right.similarity - left.similarity);
  }

  async findKnowledgeGaps(question: string): Promise<readonly string[]> {
    const gaps: string[] = [];
    if (!question.toLowerCase().includes("evidence"))
      gaps.push("Evidence expectations are not explicit.");
    if (!question.toLowerCase().includes("context"))
      gaps.push("Context and scope need clarification.");
    if (question.length < 80) gaps.push("The question may need more constraints or examples.");
    return gaps;
  }

  async suggestResearch(question: string): Promise<readonly string[]> {
    return [
      `Run a literature and dataset search for: ${question}`,
      "Identify competing explanations and missing evidence."
    ];
  }

  async suggestProjects(
    question: string
  ): Promise<readonly import("./contracts.js").QuestionToProjectPlan[]> {
    return [
      {
        title: `Project from question: ${question.slice(0, 60)}`,
        goal: "Turn the question into a reproducible exploration plan.",
        researchPlan: await this.suggestResearch(question),
        milestones: ["Clarify scope", "Collect evidence", "Generate report"],
        tasks: ["Refine question", "Create evidence list", "Run Semantiq preview"],
        requiredData: [],
        requiredTools: ["Knowledge Graph", "Semantiq"],
        agentsNeeded: ["question-refiner", "evidence", "review"],
        expectedOutputs: ["Question profile", "Evidence map", "Project plan"],
        risks: ["Insufficient context"],
        successCriteria: ["Question has evidence, scope, and next actions."]
      }
    ];
  }

  async suggestNarratives(question: string): Promise<readonly string[]> {
    return [`Create a learning journey that starts with "${this.normalizeQuestion(question)}"`];
  }

  async suggestCommunities(question: string): Promise<readonly string[]> {
    const intent = await this.extractIntent(question);
    return intent.intents.map((item) => `${item.intent}-community`);
  }

  async extractIntent(question: string): Promise<IntentAnalysis> {
    const lower = question.toLowerCase();
    const intents: IntentAnalysis["intents"] = [
      lower.includes("build") || lower.includes("project")
        ? {
            intent: "project-creation",
            confidence: 0.6,
            explanation: "Question contains project/build language."
          }
        : {
            intent: "learning",
            confidence: 0.4,
            explanation: "Default local scaffold intent for exploratory questions."
          }
    ];
    return { intents };
  }

  async analyzeAmbiguity(question: string): Promise<AmbiguityReport> {
    return {
      ambiguities:
        question.length < 40
          ? [
              {
                area: "context",
                explanation:
                  "Short questions often need more context for high-quality exploration.",
                clarificationQuestion:
                  "What context, audience, or constraints should this question include?",
                confidence: 0.5
              }
            ]
          : []
    };
  }

  async detectAssumptions(question: string): Promise<AssumptionReport> {
    return {
      assumptions: question.includes("best")
        ? [
            {
              type: "definition",
              statement: "The word best assumes shared evaluation criteria.",
              explanation:
                "Clarify what best means: fastest, safest, most educational, most rigorous, or most practical.",
              confidence: 0.7
            }
          ]
        : []
    };
  }

  async suggestTags(question: string): Promise<readonly SemanticTagSuggestion[]> {
    const tags: SemanticTagSuggestion[] = [];
    if (question.includes("?")) {
      tags.push({
        tag: "question",
        layer: "intent",
        confidence: 0.5,
        explanation: "Input is framed as a question."
      });
    }
    return tags;
  }

  async generateSemantiqPreview(question: string): Promise<SemantiqPreview> {
    const lengthScore = Math.min(1, question.trim().length / 160);
    return {
      questionQuality: lengthScore,
      clarity: question.includes("?") ? 0.7 : 0.4,
      novelty: 0.5,
      scientificPotential: 0.5,
      evidenceGap: 0.8,
      ambiguity: question.length < 40 ? 0.7 : 0.3,
      risk: 0.2,
      suggestedImprovements: ["Add context, scope, and evidence expectations before publishing."],
      finalBenchmark: false
    };
  }

  async approveSuggestion(suggestionId: string): Promise<IntelligenceSuggestion> {
    return this.updateSuggestion(suggestionId, "approved");
  }

  async rejectSuggestion(suggestionId: string): Promise<IntelligenceSuggestion> {
    return this.updateSuggestion(suggestionId, "rejected");
  }

  private remember<TPayload>(
    suggestion: IntelligenceSuggestion<TPayload>
  ): IntelligenceSuggestion<TPayload> {
    this.suggestions.set(suggestion.id, suggestion);
    return suggestion;
  }

  private updateSuggestion(
    suggestionId: string,
    status: "approved" | "rejected"
  ): IntelligenceSuggestion {
    const suggestion = this.suggestions.get(suggestionId);
    if (!suggestion) {
      throw new Error(`Suggestion not found: ${suggestionId}`);
    }
    const updated = { ...suggestion, status };
    this.suggestions.set(suggestionId, updated);
    return updated;
  }

  private normalizeQuestion(input: string): string {
    const trimmed = input.trim();
    return trimmed.endsWith("?") ? trimmed : `${trimmed}?`;
  }
}
