"""
SemantIQ Python SDK.

First-class Python SDK for Autonomous Agent Behavioral Benchmarking, Governed Evidence, and Reproducibility Verification.
"""
from .client import SemantiqClient
from .contracts import (
    PRODUCT_CONTRACTS_SCHEMA_VERSION,
    EPISTEMIC_CAUSAL_DISCLAIMER,
    EPISTEMIC_GOVERNANCE_DISCLAIMER,
    EPISTEMIC_LANGUAGE_DISCLAIMER,
    EPISTEMIC_REPRODUCIBILITY_DISCLAIMER,
    EPISTEMIC_ROBUSTNESS_DISCLAIMER,
    EPISTEMIC_BUNDLE_DISCLAIMER,
    EPISTEMIC_REPLICATION_DISCLAIMER,
    EPISTEMIC_PREREGISTRATION_DISCLAIMER,
    EPISTEMIC_MANIFEST_DISCLAIMER,
    EPISTEMIC_GATE_DISCLAIMER,
    Benchmark,
    BootstrapConfidenceInterval,
    BundleComponentArtifact,
    BundleVerificationResult,
    Case,
    Claim,
    ClaimAssertionType,
    ClaimStatus,
    ContextDiversityDimension,
    ControlledLanguageValidationResult,
    ControlledLanguageViolation,
    CrossOrgReplicationAggregation,
    EnvironmentProfile,
    EpistemicNature,
    Evaluation,
    EvaluationResult,
    EvaluationStatus,
    EvidenceConfidence,
    EvidenceObservation,
    ExactSignTestResult,
    ExternalEvidenceEligibilityDecision,
    GovernedClaimLifecycleStatus,
    GovernedEvidenceClaim,
    ImportBundleResult,
    ManifestIngestionResult,
    MatchedContrastReport,
    MatchedRunPair,
    MemoryProfile,
    MissingDataReport,
    ModelProfile,
    NegativeControlExecution,
    ObservationCategory,
    Partner,
    PartnerAttestation,
    PartnerOrganization,
    PartnerRole,
    PartnerStudy,
    Pattern,
    PatternCategory,
    PatternSeverity,
    PopulationProfile,
    ProductRunStatus,
    ProtocolDeviation,
    ProtocolExecutionSummary,
    RedactedExchangePackage,
    Relation,
    RelationType,
    ReplicationRecord,
    ResearchBundle,
    ResearchBundleManifest,
    ResourcePressureProfile,
    Review,
    ReviewVerdict,
    ReviewerRole,
    Run,
    RunProfile,
    RunStatus,
    SoftwareFingerprints,
    Study,
    StudyExecutionManifest,
    StudyProtocol,
    StudyStatus,
    SystemProfile,
    ToolsProfile,
    Trace,
    TraceEvent,
    TraceEventSource,
    TraceEventType,
    TraceStatus,
    WorkspaceSnapshot,
    compute_sha256,
)
from .controlled_language import ControlledLanguageValidator
from .errors import (
    ControlledLanguageError,
    EvaluationError,
    GovernancePolicyError,
    InsufficientDataError,
    ReceiptVerificationError,
    SemantiqError,
    ValidationError,
)
from .fixtures import (
    mock_benchmark,
    mock_case,
    mock_governed_claim,
    mock_run_profile,
    mock_system_profile,
)
from .runner import LocalDeterministicRunner
from .version import SEMANTIQ_MATURITY, SEMANTIQ_RELEASE_VERSION

__version__ = SEMANTIQ_RELEASE_VERSION
__maturity__ = SEMANTIQ_MATURITY

__all__ = [
    "__version__",
    "__maturity__",
    "SEMANTIQ_RELEASE_VERSION",
    "SEMANTIQ_MATURITY",
    "PRODUCT_CONTRACTS_SCHEMA_VERSION",
    "EPISTEMIC_CAUSAL_DISCLAIMER",
    "EPISTEMIC_ROBUSTNESS_DISCLAIMER",
    "EPISTEMIC_REPRODUCIBILITY_DISCLAIMER",
    "EPISTEMIC_LANGUAGE_DISCLAIMER",
    "EPISTEMIC_GOVERNANCE_DISCLAIMER",
    "EPISTEMIC_BUNDLE_DISCLAIMER",
    "SemantiqClient",
    "LocalDeterministicRunner",
    "ControlledLanguageValidator",
    "compute_sha256",
    # Error Hierarchy
    "SemantiqError",
    "ValidationError",
    "EvaluationError",
    "ReceiptVerificationError",
    "InsufficientDataError",
    "ControlledLanguageError",
    "GovernancePolicyError",
    # 15 Core Entity Dataclasses
    "SystemProfile",
    "Benchmark",
    "Case",
    "Run",
    "Trace",
    "TraceEvent",
    "Pattern",
    "Relation",
    "EvidenceObservation",
    "Evaluation",
    "Claim",
    "Review",
    "Partner",
    "Study",
    "ResearchBundle",
    # Governed & Statistical Models
    "GovernedEvidenceClaim",
    "ControlledLanguageViolation",
    "ControlledLanguageValidationResult",
    "EnvironmentProfile",
    "ModelProfile",
    "PopulationProfile",
    "ToolsProfile",
    "MemoryProfile",
    "ResourcePressureProfile",
    "RunProfile",
    "MatchedRunPair",
    "BootstrapConfidenceInterval",
    "ExactSignTestResult",
    "MatchedContrastReport",
    # Research Bundle Models
    "SoftwareFingerprints",
    "WorkspaceSnapshot",
    "BundleComponentArtifact",
    "ResearchBundleManifest",
    "BundleVerificationResult",
    # Partner Exchange, Protocol, Manifest & Eligibility Gate Models
    "EPISTEMIC_REPLICATION_DISCLAIMER",
    "EPISTEMIC_PREREGISTRATION_DISCLAIMER",
    "EPISTEMIC_MANIFEST_DISCLAIMER",
    "EPISTEMIC_GATE_DISCLAIMER",
    "PartnerOrganization",
    "PartnerStudy",
    "ContextDiversityDimension",
    "ReplicationRecord",
    "RedactedExchangePackage",
    "CrossOrgReplicationAggregation",
    "StudyProtocol",
    "ProtocolDeviation",
    "ProtocolExecutionSummary",
    "MissingDataReport",
    "NegativeControlExecution",
    "PartnerAttestation",
    "StudyExecutionManifest",
    "ManifestIngestionResult",
    "ExternalEvidenceEligibilityDecision",
    # Workflow Results
    "EvaluationResult",
    "ImportBundleResult",
    # Enums
    "RunStatus",
    "ProductRunStatus",
    "TraceStatus",
    "TraceEventType",
    "TraceEventSource",
    "PatternCategory",
    "PatternSeverity",
    "EvidenceConfidence",
    "EpistemicNature",
    "RelationType",
    "ObservationCategory",
    "EvaluationStatus",
    "ClaimAssertionType",
    "ClaimStatus",
    "GovernedClaimLifecycleStatus",
    "ReviewerRole",
    "ReviewVerdict",
    "PartnerRole",
    "StudyStatus",
    # Fixtures
    "mock_system_profile",
    "mock_benchmark",
    "mock_case",
    "mock_run_profile",
    "mock_governed_claim",
]
