"""
SemantIQ Python SDK.

First-class Python SDK for Autonomous Agent Behavioral Benchmarking and Evidence Verification.
"""
from .client import SemantiqClient
from .contracts import (
    PRODUCT_CONTRACTS_SCHEMA_VERSION,
    Benchmark,
    Case,
    Claim,
    ClaimAssertionType,
    ClaimStatus,
    EpistemicNature,
    Evaluation,
    EvaluationStatus,
    EvidenceConfidence,
    EvidenceObservation,
    ObservationCategory,
    Partner,
    PartnerRole,
    Pattern,
    PatternCategory,
    PatternSeverity,
    Relation,
    RelationType,
    ResearchBundle,
    Review,
    ReviewVerdict,
    ReviewerRole,
    Run,
    RunStatus,
    Study,
    StudyStatus,
    SystemProfile,
    Trace,
    TraceEvent,
    TraceEventSource,
    TraceEventType,
    TraceStatus,
)
from .errors import (
    EvaluationError,
    InsufficientDataError,
    ReceiptVerificationError,
    SemantiqError,
    ValidationError,
)
from .runner import LocalDeterministicRunner

__version__ = "0.1.0a2"

__all__ = [
    "__version__",
    "PRODUCT_CONTRACTS_SCHEMA_VERSION",
    "SemantiqClient",
    "LocalDeterministicRunner",
    "SemantiqError",
    "ValidationError",
    "EvaluationError",
    "ReceiptVerificationError",
    "InsufficientDataError",
    "SystemProfile",
    "Benchmark",
    "Case",
    "Run",
    "Trace",
    "TraceEvent",
    "Pattern",
    "Relation",
    "EvidenceObservation",
    "Evaluation",
    "Claim",
    "Review",
    "Partner",
    "Study",
    "ResearchBundle",
    "RunStatus",
    "TraceStatus",
    "TraceEventType",
    "TraceEventSource",
    "PatternCategory",
    "PatternSeverity",
    "EvidenceConfidence",
    "EpistemicNature",
    "RelationType",
    "ObservationCategory",
    "EvaluationStatus",
    "ClaimAssertionType",
    "ClaimStatus",
    "ReviewerRole",
    "ReviewVerdict",
    "PartnerRole",
    "StudyStatus",
]
